### ISSUE TITLE
One issue that is NOT relevant SINCE NOW and IS FALSE

### ISSUE THREAD

**Issue by asmexcaliburwoods** [tranoo/tranoo#9]
My parts of Tranoo PrimsToMesh, AHTracker, and the website's source code will probably be published on https://github.com/Tranoo under liberal Apache 2.0 and LGPL licenses.

**Comment by asmexcaliburwoods** [comment]
https://marketplace.secondlife.com/stores/164165 

Tranoo Store (Closed)

The website is at: http://tranoo.com/

Our service will function 6 months since Jan 2022, and then will be closed. Service and products don't pay for the time for software development & maintenance. We simply can't afford it, it eats a lot of time and pays very very little.

The partial source code for the Tranoo products (Eugene Gr. Philippov's parts) should be published opensource with liberal licenses (Apache 2.0, probably, plus LGPL) on https://github.com/Tranoo

**Comment by tattwamasii2p** [comment]
WAS: "Our service is closing in 6 months from now."; THIS IS WRONG; IN PROCESSES OF HEALING ALL THE STUFF TRANOO SHOP & SERVICES.
